name: bookmark_models
description: Models held for bookmark.vhcblade.com
version: 0.1.0
repository: https://github.com/VHCBlade/bookmark_models

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  event_db: ^0.1.6

  tuple: ^2.0.0
  uuid: ^3.0.7
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
